# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [3]:
%run initialise.py

ModuleNotFoundError: No module named 'nbformat'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
np.show_config()

1.23.4
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [10]:
v = np.zeros((10,10))
# print(v)
print("%d bytes" % (v.size * v.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
v = np.zeros(10)
print(v)
v[4] = 1
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [19]:
v = np.arange(10)
v = v[::-1]
print(v)

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
v = np.arange(9).reshape(3,3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [23]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [25]:
IM = np.eye(3,3)
print(IM)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [28]:
d3 = np.random.random((3,3,3))
print(d3)

[[[0.80704985 0.23135296 0.33252253]
  [0.05696531 0.84018703 0.54223253]
  [0.0286345  0.6120247  0.77248498]]

 [[0.54811556 0.28098344 0.29697301]
  [0.15974309 0.47097022 0.2526494 ]
  [0.24902725 0.57605282 0.66645746]]

 [[0.08583562 0.96239537 0.05696854]
  [0.66135137 0.32532382 0.89302065]
  [0.70301381 0.21603791 0.38749125]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [32]:
arr = np.random.random((10,10))
print(arr)
arr_min ,arr_max = arr.min() , arr.max()
print(f"The min value is : {arr_min}\nThe max value is : {arr_max}")

[[9.77791950e-02 9.86447203e-01 5.59395390e-01 5.89679850e-01
  5.72580077e-01 6.02222656e-02 4.62074850e-01 1.73949471e-02
  8.90205321e-01 8.31900077e-01]
 [2.04366841e-01 1.10771566e-01 3.11035391e-01 3.45321306e-02
  4.02586319e-01 5.94525682e-01 8.44005739e-01 3.04821311e-01
  9.81108006e-01 5.58909951e-01]
 [3.43784044e-01 9.22178506e-01 7.66748359e-01 6.89818039e-01
  8.58416000e-01 8.34083238e-01 8.15282541e-01 5.16080980e-01
  3.94916804e-02 9.80146524e-01]
 [2.42949434e-01 3.54239505e-01 6.79253888e-01 8.48237726e-02
  5.36521473e-01 7.17347270e-01 3.93636949e-01 6.29149048e-01
  8.04238935e-01 1.73641503e-01]
 [9.40511821e-01 4.91690224e-01 7.25952784e-01 1.41944966e-01
  6.59461159e-01 1.87271880e-01 3.37974127e-01 8.43735099e-01
  8.45047949e-01 8.13052510e-01]
 [2.23572506e-01 1.29681653e-02 2.03457436e-01 8.44933604e-01
  5.28742424e-01 4.91915183e-01 8.30804321e-03 3.10209243e-01
  5.96879371e-01 6.09576537e-01]
 [6.31416469e-01 4.69630383e-01 1.62489887e-01 1.62007968e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
v = np.random.random(30)
mn = v.mean()
print(mn)

0.521230129921385


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [35]:
d2 = np.ones((6,6))
d2[1:-1,1:-1] = 0
print(d2)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [3]:
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [5]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [2]:
arr = np.diag(1+np.arange(4), k=0)
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [8]:
mt = np.zeros((8,8),dtype=int)
mt[1::2, ::2] = 1
mt[::2, 1::2] = 1
print(mt)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [9]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [11]:
mt = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(mt)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [14]:
mt = np.random.random((5,5))
mt = (mt - np.mean(mt)) / (np.std(mt))
print(mt)

[[-0.74863986 -1.32278388  0.70844735 -0.63811325  0.33129472]
 [-1.16892971 -1.15252758  0.77189764 -0.78664799 -0.68369624]
 [ 0.14731389 -0.10179159 -1.16038744 -0.07175276  0.41943461]
 [ 0.20276677 -1.38735906  0.36930653  1.56867302  0.64940758]
 [-1.51030611  1.3941201   0.69464193  1.77417192  1.7014594 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [16]:
colr = np.dtype([("r" , np.ubyte),
                ("g" , np.ubyte),
                ("b" , np.ubyte),
                ("a" , np.ubyte)])
print(colr)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [17]:
mul_mt = np.dot(np.ones((5,3)), np.ones((3,2)))
print(mul_mt)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [18]:
v = np.arange(11)
v[(3 < v) & (v < 8)] *= -1
print(v)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [19]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'list'

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [22]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\User\AppData\Local\Temp\ipykernel_2808\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\User\AppData\Local\Temp\ipykernel_2808\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [4]:
v = np.random.uniform(-10,+10,10)
# print(v)
print(np.where(v>0 ,np.ceil(v), np.floor(v)))

[-10.  -8.  -3.  -7. -10.  -8.  -9.  -8.   8.   6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [6]:
v1 = np.random.randint(0,10,10)
print(v1)
v2 = np.random.randint(0,10,10)
print(v2)
print(np.intersect1d(v1,v2))

[0 6 9 7 9 8 8 8 6 6]
[9 8 0 8 4 4 1 8 6 5]
[0 6 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [7]:
np.sqrt(-1) == np.emath.sqrt(-1)
# false

C:\Users\User\AppData\Local\Temp\ipykernel_3704\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [12]:
yesterday = np.datetime64('today') - 1
print(yesterday)
today = np.datetime64('today')
print(today)
tomorrow = np.datetime64('today') + 1
print(tomorrow)

2022-10-22
2022-10-23
2022-10-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [13]:
dates = np.arange('2016-07' , '2016-08' , dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [14]:
v = np.random.uniform(0,10,10)
print(v)
print(v - v%1)
print(v // 1)
print(np.floor(v))
print(v.astype(int))
print(np.trunc(v))

[5.2953823  9.76938427 1.95367544 3.88668953 5.61456968 2.50272496
 0.54678099 1.5216611  2.21938919 4.43891846]
[5. 9. 1. 3. 5. 2. 0. 1. 2. 4.]
[5. 9. 1. 3. 5. 2. 0. 1. 2. 4.]
[5. 9. 1. 3. 5. 2. 0. 1. 2. 4.]
[5 9 1 3 5 2 0 1 2 4]
[5. 9. 1. 3. 5. 2. 0. 1. 2. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [19]:
ar = np.tile(np.arange(0,5) , (5,1))
print(ar)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [2]:
def generate():
    for i in range(11):
        yield i

ar = np.fromiter(generate() , dtype=int , count=-1)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [6]:
v = np.linspace(0,1,11,endpoint=False)[1:]
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [8]:
v = np.random.random(10)
v.sort()
print(v)

[0.0879458  0.25236665 0.26780732 0.34042541 0.36880398 0.4933066
 0.61883963 0.71864344 0.77898783 0.88317501]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [10]:
v = np.arange(10)
print(v)
np.add.reduce(v)

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [16]:
A = np.random.random(10)
print(A)
B = np.random.random(10)
print(B)
print(A==B)

[0.88875321 0.16854552 0.73550199 0.79826119 0.89173408 0.63503722
 0.66165098 0.46646965 0.15549665 0.95315724]
[0.02592539 0.13839741 0.92296151 0.18100595 0.61743746 0.32895637
 0.57609306 0.33842716 0.85331003 0.81965976]
[False False False False False False False False False False]


#### 43. Make an array immutable (read-only) (★★☆)

In [3]:
ar = np.arange(10)
print(ar)
ar.flags.writeable = False
ar[0] = 1
print(ar)

[0 1 2 3 4 5 6 7 8 9]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [6]:
v = np.random.random((10,2))
print(v)
x , y  = v[:,0] , v[:,1]
# print(x)
# print(y)
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)


[[0.27635967 0.8906613 ]
 [0.30043149 0.13054137]
 [0.92579062 0.88336473]
 [0.84279595 0.00600483]
 [0.65579971 0.48657458]
 [0.83755581 0.58360605]
 [0.58387931 0.96811563]
 [0.21363962 0.72254903]
 [0.21091737 0.87181691]
 [0.41992137 0.41648137]]
[0.93255146 0.32756699 1.27961772 0.84281734 0.81659542 1.02083091
 1.13055868 0.75347129 0.89696759 0.59143105]
[1.26992982 0.40990053 0.7619518  0.00712477 0.6383331  0.6085728
 1.02809389 1.28331222 1.33342866 0.78128534]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [5]:
v  =np.random.random(10)
v[v.argmax()]  = 0
print(v)

[0.72934028 0.70690186 0.6498513  0.4749042  0.41624793 0.
 0.1534919  0.75416138 0.84326109 0.11469836]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [7]:
ar = np.zeros((5,5), [('x',float),('y',float)])
ar['x'], ar['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(ar)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [8]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [9]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [11]:
np.set_printoptions(threshold=float("inf"))
ar = np.zeros((10,10))
print(ar)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [12]:
ar = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(ar-v)).argmin()
print(ar[index])

56


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [14]:
ar = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(ar)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\User\AppData\Local\Temp\ipykernel_9832\3210695669.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ar = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [16]:

import scipy
import scipy.spatial

v = np.random.random((10,2))
d = scipy.spatial.distance.cdist(v,v)
print(d)

ModuleNotFoundError: No module named 'scipy'

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [17]:
v = (np.random.rand(10)*100).astype(np.float32)
y = v.view(np.int32)
y[:] = v
print(y)

[40 16 90 92 67 80 72 77 42  2]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [18]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
v = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(v)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\User\AppData\Local\Temp\ipykernel_9832\784727607.py:9: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  v = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [19]:
v = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(v):
    print(index, value)
for index in np.ndindex(v.shape):
    print(index, v[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [20]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [21]:
n = 10
p = 3
v = np.zeros((n,n))
np.put(v, np.random.choice(range(n*n), p, replace=False),1)
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [22]:
x = np.random.rand(5, 10)

y = x - x.mean(axis=1, keepdims=True)

y = x - x.mean(axis=1).reshape(-1, 1)

print(y)

[[-0.19664402  0.50343869  0.48626406 -0.01999789 -0.10048877  0.18963965
  -0.42176125 -0.40463234  0.07464653 -0.11046466]
 [-0.39063392 -0.35815903 -0.24177173  0.07841348  0.02583523  0.39983155
   0.34418451  0.11744352 -0.18080188  0.20565828]
 [-0.03964195 -0.12769484 -0.17355413 -0.31624144 -0.43368842  0.4240272
  -0.28062609  0.4236511   0.10383914  0.41992943]
 [-0.25201839  0.00445809  0.2807782  -0.24129572  0.44647731 -0.35066672
  -0.05344581 -0.18809826  0.35024596  0.00356534]
 [ 0.50319548  0.08133656  0.50050793 -0.41644312 -0.27395292 -0.28544093
  -0.16410288 -0.01269195  0.27118221 -0.20359038]]


#### 59. How to sort an array by the nth column? (★★☆)

In [23]:
ar = np.random.randint(0,10,(3,3))
print(ar)
print(ar[ar[:,1].argsort()])

[[2 7 4]
 [6 1 7]
 [1 5 4]]
[[6 1 7]
 [1 5 4]
 [2 7 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [24]:
ar = np.random.randint(0,3,(3,10))
print((~ar.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [25]:
ar = np.random.uniform(0,1,10)
z = 0.5
m = ar.flat[np.abs(ar - z).argmin()]
print(m)

0.5959751473308258


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [26]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [27]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

ar = NamedArray(np.arange(10), "range_10")
print (ar.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [28]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
z += np.bincount(i, minlength=len(z))

np.add.at(z, i, 1)
print(z)

[7. 5. 3. 7. 1. 5. 3. 9. 3. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [29]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f = np.bincount(i,x)
print(f)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [30]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [31]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[46 51 45 51]
 [45 54 55 69]
 [35 67 60 48]]
[[46 51 45 51]
 [45 54 55 69]
 [35 67 60 48]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)